import Head from 'next/head';
import Banner from './components/Banner';
import About from './components/About';
import styles from './page.module.css';
import BodyOfWork from './components/bodyofwork';
import Accolades from './components/Accolades';
import Nominations from './components/nominations';
import Press from './components/press';


export default function Home() {
  return (
    <div className={styles.back}>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <section>
      <div className={styles.back}></div>
          <Banner />
        </section>
        <section><About></About></section>
        <section><BodyOfWork></BodyOfWork></section>
        <section><Nominations></Nominations></section>
        <section><Accolades></Accolades></section>
        
        <section><Press></Press></section>

        
      </main>
    </div>
  );
}